baseURL = 'https://main--ornate-churros-407dd9.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'Hugo_profile'

[Params]
    favicon = '/img/merry_christmas.jpg'
    tomte_link = 'https://main--ornate-churros-407dd9.netlify.app/profile/'